In [13]:
import numpy as np
from desdeo_mcdm.interactive.NautilusNavigator import NautilusNavigator
from sklearn.preprocessing import MinMaxScaler

In [14]:
#-return, risk, -esg
F = np.load("./data/F.npy")
F[:,0] = F[:,0]
F[:,1] = F[:,1]

scaler = MinMaxScaler()
Fn = scaler.fit_transform(F)

ideal = np.min(Fn, axis=0)
nadir = np.max(Fn, axis=0)

method = NautilusNavigator(Fn, ideal, nadir)

req_first = method.start()
print(req_first)
print(req_first.content.keys())
print(req_first.content["message"])
print(req_first.content["reachable_lb"])
print(req_first.content["reachable_ub"])


dict_keys(['message', 'ideal', 'nadir', 'reachable_lb', 'reachable_ub', 'user_bounds', 'reachable_idx', 'step_number', 'steps_remaining', 'distance', 'allowed_speeds', 'current_speed', 'navigation_point'])
Please supply aspirations levels for each objective between the upper and lower bounds as `reference_point`. Specify a speed between 1-5 as `speed`. If going to a previous step is desired, please set `go_to_previous` to True, otherwise it should be False. Bounds for one or more objectives may also be specified as 'user_bounds'; when navigating,the value of the objectives present in the navigation points will not exceed the valuesspecified in 'user_bounds'.Lastly, if stopping is desired, `stop` should be True, otherwise it should be set to False.
[0. 0. 0.]
[1. 1. 1.]


In [15]:
response = {
    "reference_point": np.array([0.4, 0.8, 0.5]),
    "go_to_previous": False,
    "stop": False,
    "speed": 1,
    "user_bounds": np.array([1,1,1])
}

req_first.response = response
req_snd = method.iterate(req_first)

print(req_snd.content["reachable_lb"])
print(req_snd.content["reachable_ub"])

[0.00620815 0.         0.        ]
[1.         0.96680264 0.99767735]


In [16]:
previous_requests = [req_first, req_snd]
req = req_snd
while method._step_number < 100:
    req.response = response
    req = method.iterate(req)

    previous_requests.append(req)

print(req.content["reachable_lb"])
print(req.content["reachable_ub"])
print(req.content["step_number"])

print(req.content["reachable_idx"])

[0.22070354 0.41366035 0.37745351]
[0.22070354 0.41366035 0.37745351]
100
57
