In [9]:
import numpy as np
from desdeo_mcdm.interactive.NautilusNavigator import NautilusNavigator
from sklearn.preprocessing import MinMaxScaler

In [10]:
#-return, risk, -esg
F = np.load("./data/F.npy")
F[:,0] = F[:,0]
F[:,1] = F[:,1]

scaler = MinMaxScaler()
Fn = scaler.fit_transform(F)

ideal = np.min(Fn, axis=0)
nadir = np.max(Fn, axis=0)

method = NautilusNavigator(Fn, ideal, nadir)

req_first = method.start()
print(req_first)
print(req_first.content.keys())
print(req_first.content["message"])
print(req_first.content["reachable_lb"])
print(req_first.content["reachable_ub"])


dict_keys(['message', 'ideal', 'nadir', 'reachable_lb', 'reachable_ub', 'user_bounds', 'reachable_idx', 'step_number', 'steps_remaining', 'distance', 'allowed_speeds', 'current_speed', 'navigation_point'])
Please supply aspirations levels for each objective between the upper and lower bounds as `reference_point`. Specify a speed between 1-5 as `speed`. If going to a previous step is desired, please set `go_to_previous` to True, otherwise it should be False. Bounds for one or more objectives may also be specified as 'user_bounds'; when navigating,the value of the objectives present in the navigation points will not exceed the valuesspecified in 'user_bounds'.Lastly, if stopping is desired, `stop` should be True, otherwise it should be set to False.
[0. 0. 0.]
[1. 1. 1.]


In [11]:
response = {
    "reference_point": np.array([0.4, 0.8, 0.5]),
    "go_to_previous": False,
    "stop": False,
    "speed": 1,
    "user_bounds": np.array([1,1,1])
}

req_first.response = response
req_snd = method.iterate(req_first)

print(req_snd.content["reachable_lb"])
print(req_snd.content["reachable_ub"])

[0.00620815 0.         0.        ]
[1.         0.96680264 0.99767735]


In [12]:
previous_requests = [req_first, req_snd]
req = req_snd
while method._step_number < 100:
    req.response = response
    req = method.iterate(req)

    previous_requests.append(req)

print(req.content["reachable_lb"])
print(req.content["reachable_ub"])
print(req.content["step_number"])

print(req.content["reachable_idx"])

[0.06487542 0.03295414 0.        ]
[0.90541127 0.73603404 0.82531967]
30
[ 2  8 10 11 13 14 15 16 17 18 20 21 22 23 24 27 28 29 30 32 33 34 35 37
 38 39 40 41 42 43 44 45 46 47 49 50 51 52 54 55 57 58 59 60 61 62 64 65
 66 68 69 70 72 73 74 75 76 77 78 80 81 82 83 84 86 87 88 89 90 92 93 94
 95 96 97 98]
